export type Anchor = "left" | "right" | "top" | "bottom";

/**
 * Pin positions on the dotted world map (viewBox 103×52) as percentages.
 *
 * These stay in code on purpose: Qatar does not move, and asking an admin to
 * enter map coordinates is a good way to get a pin in the Atlantic. The admin
 * panel edits names, worker counts, visibility and order; anything without an
 * entry here isn't offered in the picker.
 *
 * HOW TO ADD A COUNTRY
 * The background map is generated by `dotted-map` with these exact settings:
 *
 *     new DottedMap({ height: 52, grid: "diagonal", projection: { name: "mercator" } })
 *
 * (confirmed by regenerating and matching both the viewBox and the 2,292-dot
 * count of public/images/world-dotted.svg). To place a new pin, add it through
 * the same library and read back its position, rather than eyeballing:
 *
 *     const m = new DottedMap({ height: 52, grid: "diagonal", projection: { name: "mercator" } });
 *     m.addPin({ lat, lng, svgOptions: { color: "#f0f", radius: 0.9 } });
 *     // find the r="0.9" circle in m.getSVG(...) → left = cx/103*100, top = cy/52*100
 *
 * Two things to check on anything you add:
 *  - `left` must stay under 99.5 — that is the map's easternmost dot. Pins
 *    computed beyond it (New Zealand lands at 102.4) render outside the image.
 *  - Small neighbours can snap to the same dot; nudge by a few tenths so the
 *    markers don't stack. Cyprus is nudged off Lebanon's dot below.
 *
 * `anchor` is which side of the pin a callout pill hangs off, chosen so the
 * tightly-packed Gulf labels don't collide.
 *
 * Safe to import from client components — plain data, no server imports.
 */
export const REACH_COORDS: Record<string, { left: number; top: number; anchor: Anchor }> = {
  // ── Gulf ────────────────────────────────────────────────────────────────
  // Hand-nudged apart; these six sit within a couple of dots of each other.
  sa: { left: 63.1, top: 45.0, anchor: "left" }, // Saudi Arabia
  ae: { left: 66.0, top: 45.0, anchor: "right" }, // United Arab Emirates
  om: { left: 66.5, top: 46.6, anchor: "right" }, // Oman
  qa: { left: 65.1, top: 45.0, anchor: "right" }, // Qatar
  kw: { left: 64.1, top: 41.6, anchor: "top" }, // Kuwait
  bh: { left: 65.1, top: 44.4, anchor: "right" }, // Bahrain

  // ── Wider Middle East ───────────────────────────────────────────────────
  jo: { left: 61.2, top: 41.6, anchor: "left" }, // Jordan
  iq: { left: 63.6, top: 40.0, anchor: "right" }, // Iraq
  lb: { left: 60.2, top: 38.3, anchor: "right" }, // Lebanon
  cy: { left: 59.6, top: 37.4, anchor: "right" }, // Cyprus — nudged off Lebanon
  tr: { left: 60.2, top: 35.0, anchor: "right" }, // Türkiye
  az: { left: 65.0, top: 35.0, anchor: "right" }, // Azerbaijan

  // ── North & Sub-Saharan Africa ──────────────────────────────────────────
  eg: { left: 59.2, top: 41.6, anchor: "right" }, // Egypt
  ly: { left: 53.9, top: 40.0, anchor: "right" }, // Libya
  sd: { left: 59.2, top: 51.6, anchor: "right" }, // Sudan
  za: { left: 58.7, top: 76.6, anchor: "right" }, // South Africa
  mu: { left: 67.0, top: 71.6, anchor: "right" }, // Mauritius
  sc: { left: 66.5, top: 63.3, anchor: "right" }, // Seychelles

  // ── Asia-Pacific ────────────────────────────────────────────────────────
  my: { left: 80.6, top: 58.3, anchor: "bottom" }, // Malaysia
  sg: { left: 81.1, top: 60.0, anchor: "left" }, // Singapore
  bn: { left: 84.0, top: 56.6, anchor: "left" }, // Brunei
  th: { left: 79.6, top: 51.6, anchor: "left" }, // Thailand
  hk: { left: 84.0, top: 46.6, anchor: "left" }, // Hong Kong
  cn: { left: 84.5, top: 35.0, anchor: "left" }, // China
  kr: { left: 87.9, top: 36.6, anchor: "left" }, // South Korea
  jp: { left: 91.3, top: 38.3, anchor: "left" }, // Japan
  mv: { left: 71.8, top: 58.3, anchor: "right" }, // Maldives
  lk: { left: 73.3, top: 56.6, anchor: "left" }, // Sri Lanka
  au: { left: 95.1, top: 81.6, anchor: "left" }, // Australia

  // ── Europe ──────────────────────────────────────────────────────────────
  it: { left: 53.9, top: 33.3, anchor: "right" }, // Italy
  gr: { left: 56.8, top: 36.6, anchor: "right" }, // Greece
  mt: { left: 54.4, top: 38.3, anchor: "right" }, // Malta
  pt: { left: 47.6, top: 35.0, anchor: "right" }, // Portugal
  es: { left: 48.5, top: 35.0, anchor: "right" }, // Spain
  gb: { left: 49.5, top: 25.0, anchor: "right" }, // United Kingdom
  ie: { left: 48.1, top: 23.3, anchor: "right" }, // Ireland
  de: { left: 53.9, top: 23.3, anchor: "right" }, // Germany
  nl: { left: 51.9, top: 23.3, anchor: "right" }, // Netherlands
  pl: { left: 55.8, top: 23.3, anchor: "right" }, // Poland
  cz: { left: 53.9, top: 26.6, anchor: "right" }, // Czechia
  hu: { left: 55.3, top: 28.3, anchor: "right" }, // Hungary
  ro: { left: 58.3, top: 31.6, anchor: "right" }, // Romania
  hr: { left: 54.9, top: 30.0, anchor: "right" }, // Croatia
  rs: { left: 55.8, top: 30.0, anchor: "right" }, // Serbia
  ru: { left: 61.7, top: 20.0, anchor: "right" }, // Russia

  // ── Central Asia & Americas ─────────────────────────────────────────────
  kz: { left: 70.9, top: 25.0, anchor: "right" }, // Kazakhstan
  ca: { left: 27.7, top: 30.0, anchor: "right" }, // Canada
};

/** Country codes that can be placed on the map, for the admin picker. */
export const REACH_CODES = Object.keys(REACH_COORDS);

/**
 * The head-office marker. Hardcoded rather than stored: it is not a
 * destination market, carries no worker count, and should not be deletable
 * from a CMS by accident.
 */
export const HQ = {
  code: "bd",
  left: 77.2,
  top: 46.6,
  anchor: "top" as Anchor,
};
